# Generated by Django 6.0.7 on 2026-07-12 18:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('learners', '0002_rename_guardian_info_learner_parent_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('record_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level_completed', models.CharField(max_length=100)),
                ('academic_year', models.CharField(max_length=20)),
                ('subject_results', models.JSONField(default=dict, help_text="Finalized per-subject results, e.g. {'Math': 87, 'English': 72}.")),
                ('completion_outcome', models.CharField(choices=[('PASSED', 'Passed'), ('PROMOTED', 'Promoted'), ('OTHER', 'Other')], default='PROMOTED', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SIGNED', 'Signed'), ('SYNCED', 'Synced')], default='DRAFT', max_length=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issued_records', to='accounts.institution')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='learners.learner')),
            ],
        ),
        migrations.CreateModel(
            name='DigitalSignature',
            fields=[
                ('record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='signature', serialize=False, to='records.academicrecord')),
                ('signature_value', models.TextField(help_text='Base64 Ed25519 signature (64 bytes).')),
                ('record_hash', models.CharField(help_text='SHA-256 hex of the canonical payload.', max_length=64)),
                ('issuer_id', models.UUIDField()),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
