# Generated by Django 6.0.7 on 2026-07-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicrecord',
            name='completion_outcome',
            field=models.CharField(choices=[('PASSED', 'Passed'), ('PROMOTED', 'Promoted'), ('FAILED', 'Failed'), ('OTHER', 'Other')], default='PROMOTED', max_length=10),
        ),
    ]
