# Generated by Django 6.0.7 on 2026-07-27 08:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationLog',
            fields=[
                ('log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_id', models.UUIDField(help_text='The record that was checked (may be external).')),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.CharField(choices=[('AUTHENTIC', 'Authentic'), ('INVALID', 'Invalid')], max_length=10)),
                ('mode', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='ONLINE', max_length=10)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verifications', to='accounts.institution')),
            ],
        ),
    ]
