# Generated by Django 6.0.7 on 2026-07-12 13:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('learner_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('photograph', models.ImageField(blank=True, null=True, upload_to='learner_photos/')),
                ('photo_source', models.CharField(choices=[('LIVE', 'Live capture'), ('UPLOAD', 'Upload (fallback)')], default='LIVE', help_text='LIVE is higher-assurance; UPLOAD is a flagged fallback for learners who cannot be captured live.', max_length=10)),
                ('date_or_estimated_age', models.CharField(blank=True, help_text='Exact DOB or estimated age, since many learners lack birth records.', max_length=50)),
                ('guardian_info', models.CharField(blank=True, max_length=255)),
                ('place_of_origin', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_learners', to='accounts.institution')),
            ],
            options={
                'indexes': [models.Index(fields=['full_name', 'place_of_origin'], name='learners_le_full_na_8dc7cb_idx')],
            },
        ),
    ]
