# Generated by Django 6.0.7 on 2026-07-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='learner',
            old_name='guardian_info',
            new_name='parent_name',
        ),
        migrations.AddField(
            model_name='learner',
            name='parent_contact',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
